package com.aurumone.compliance.entity;

/**
 * Types of compliance alerts
 */
public enum AlertType {
    AML_SUSPICIOUS_TRANSACTION,
    KYC_VERIFICATION_REQUIRED,
    KYC_EXPIRED,
    FATCA_REPORTING_REQUIRED,
    CRS_REPORTING_REQUIRED,
    SUITABILITY_VIOLATION,
    TRANSACTION_LIMIT_EXCEEDED,
    HIGH_RISK_JURISDICTION,
    SANCTIONS_SCREENING_ALERT,
    PEP_DETECTED,
    UNUSUAL_ACTIVITY
}
