spring.application.name=portfolio-management-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/aurumone
spring.datasource.username=aurumone
spring.datasource.password=aurumone_secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

management.endpoints.web.exposure.include=health,info,metrics
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.aurumone=DEBUG
